package LHM;

import java.awt.Color;
import java.awt.Component;
import java.rmi.Naming;
//import java.rmi.RMISecurityManager;
import java.util.*;
import javax.swing.JOptionPane;


public class PatientForm extends javax.swing.JFrame {
    private Component frame;
    
    //Creates new form FrmWarehouseClient
    public PatientForm() 
        {
            initComponents();
            initWarehouse();
            CurrentDateTime();
        }
    
    //a Method to get current date and time
    public void CurrentDateTime()
        {
            Calendar cal = new GregorianCalendar();
            int month = cal.get(Calendar.MONTH);
            int year = cal.get(Calendar.YEAR);
            int day = cal.get(Calendar.DATE);
                date_txt.setText(day+"/"+(month+1)+"/"+year);
                
            int second = cal.get(Calendar.SECOND);
            int minute = cal.get(Calendar.MINUTE);
            int hour = cal.get(Calendar.HOUR);
                time_txt.setText(hour+":"+(minute));
        }
    
    //Clear method to set text value of the textfields to null
    public void Clear()
        {
            jFName.setText("");
            jSName.setText("");            
            jPatientAge.setText("");
            ResponseBox.setText("");
            DrList.clearSelection();
            HospitalList.clearSelection();
            jPatientAge.setForeground(Color.black);
            jFName.setForeground(Color.black);
            jSName.setForeground(Color.black);
        }
            
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jAgeError1 = new javax.swing.JLabel();
        jDialog1 = new javax.swing.JDialog();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jPatientAge = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        HospitalList = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ResponseBox = new javax.swing.JTextArea();
        jSubmitButton = new javax.swing.JButton();
        jExitButton = new javax.swing.JToggleButton();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jClearButton = new javax.swing.JButton();
        jFName = new javax.swing.JTextField();
        jSName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane3 = new javax.swing.JScrollPane();
        DrList = new javax.swing.JList();
        jLabel7 = new javax.swing.JLabel();
        date_txt = new javax.swing.JLabel();
        time_txt = new javax.swing.JLabel();
        Genderlist = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuFileDoctorsList = new javax.swing.JMenuItem();
        jMenuFileExit = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuEditClear = new javax.swing.JMenuItem();
        jMenuEditAoTON = new javax.swing.JMenuItem();
        jMenuEditAoTOFF = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuHelpAbout = new javax.swing.JMenuItem();

        jAgeError1.setForeground(new java.awt.Color(204, 0, 0));
        jAgeError1.setText("Error! Please enter age");
        jAgeError1.setToolTipText("x");

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LHM Appointment System");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jLabel1.setText("Age:");

        jPatientAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPatientAgeActionPerformed(evt);
            }
        });

        HospitalList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Croydon", "Chiltern", "Herefordshire", "Hillingdon", "Herefordshire", "Shropshire", "Luton", "Sutton", "Wiltshire", "Norfolk", "ValeRoyal", "London", "Bristol", "Reading" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        HospitalList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(HospitalList);

        jLabel2.setText("Please Select Hospital:");

        ResponseBox.setEditable(false);
        ResponseBox.setColumns(20);
        ResponseBox.setRows(5);
        ResponseBox.setBorder(javax.swing.BorderFactory.createTitledBorder("Response"));
        jScrollPane2.setViewportView(ResponseBox);

        jSubmitButton.setText("Submit");
        jSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSubmitButtonActionPerformed(evt);
            }
        });

        jExitButton.setText("Exit");
        jExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExitButtonActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        jLabel4.setText("Welcome to LHM appointment system");
        jLabel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jClearButton.setText("Clear");
        jClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jClearButtonActionPerformed(evt);
            }
        });

        jFName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFNameActionPerformed(evt);
            }
        });

        jSName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSNameActionPerformed(evt);
            }
        });

        jLabel5.setText("First Name:");

        jLabel6.setText("Surename:");

        DrList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Cachexia", "Loss of appetite", "Weight loss", "Weight gain", "Dry mouth", "Fatigue", "Malaise", "Asthenia", "Muscle weakness", "Pyrexia", "Jaundice", "Pain", "Abdominal pain", "Chest pain", "Bruising", "Epistaxis", "Tremor", "Convulsions", "Muscle cramps", "Tinnitus", "Dizziness", "Syncope", "Hypothermia", "Hyperthermia", "Discharge", "Bleeding", "Swelling", "Deformity", "Sweats", "Chills and shivering" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(DrList);

        jLabel7.setText("Please Select Symptom(s):");

        date_txt.setText("systemdate");

        time_txt.setText("systemtime");

        Genderlist.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));
        Genderlist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenderlistActionPerformed(evt);
            }
        });

        jLabel8.setText("Gender:");

        jMenu3.setText("File");

        jMenuFileDoctorsList.setText("Doctors List");
        jMenuFileDoctorsList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuFileDoctorsListActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuFileDoctorsList);

        jMenuFileExit.setText("Exit");
        jMenuFileExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuFileExitActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuFileExit);

        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");

        jMenuEditClear.setText("Clear");
        jMenuEditClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuEditClearActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuEditClear);

        jMenuEditAoTON.setText("Always on Top [ON]");
        jMenuEditAoTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuEditAoTONActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuEditAoTON);

        jMenuEditAoTOFF.setText("Always on Top [Off]");
        jMenuEditAoTOFF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuEditAoTOFFActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuEditAoTOFF);

        jMenuBar2.add(jMenu4);

        jMenu5.setText("Help");
        jMenu5.setToolTipText("");

        jMenuHelpAbout.setText("About");
        jMenuHelpAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuHelpAboutActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuHelpAbout);

        jMenuBar2.add(jMenu5);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator4)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jSubmitButton)
                                .addGap(234, 234, 234)
                                .addComponent(jClearButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 261, Short.MAX_VALUE)
                                .addComponent(jExitButton))
                            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator5)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(time_txt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(date_txt))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPatientAge, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSName, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jFName, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(83, 83, 83)
                                        .addComponent(jLabel8)
                                        .addGap(18, 18, 18)
                                        .addComponent(Genderlist, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addComponent(jSeparator2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addGap(188, 188, 188))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(date_txt)
                        .addComponent(time_txt)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8)
                    .addComponent(Genderlist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPatientAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSubmitButton)
                    .addComponent(jExitButton)
                    .addComponent(jClearButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    
    private void jSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSubmitButtonActionPerformed
        
        //First name validation
        if ("".equals(jFName.getText())) 
        {
            jFName.setForeground(Color.red);
            jFName.setText("Please enter your First Name !");
        }
        
        //Last name validation
        if ("".equals(jSName.getText())) 
        {
            jSName.setForeground(Color.red);
            jSName.setText("Please enter your Surname !");
        }
        
        //Age validation
        if ("".equals(jPatientAge.getText())) 
        {
            jPatientAge.setForeground(Color.red);
            jPatientAge.setText("Please enter your Age !");
            
        }        
        
        //List of hospital objects
        Object[] HospitalObjects = HospitalList.getSelectedValues();
        
        //List of Docotors objects
        Object[] DrNameObejects = DrList.getSelectedValues(); 
        
        
        String[] hobbyStrings = new String[HospitalObjects.length];
        String[] hobbyStrings1 = new String[DrNameObejects.length];
        
        System.arraycopy(HospitalObjects, 0, hobbyStrings, 0,
                HospitalObjects.length);
        
        System.arraycopy(DrNameObejects, 0, hobbyStrings1, 0,
                DrNameObejects.length);
        
        //constructor
        Patient c = new Patient(Integer.parseInt(jPatientAge.getText()),
                ((Genderlist.getSelectedIndex()==0) ? History.MALE : 0) + 
                ((Genderlist.getSelectedIndex()==1) ? History.FEMALE : 0) ,
                hobbyStrings, hobbyStrings1, jFName.getText(), jSName.getText());
        

        callWarehouse(c);

    }//GEN-LAST:event_jSubmitButtonActionPerformed

    private void jExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExitButtonActionPerformed
        //Closing the Jfram
        System.exit(0); 
        
    }//GEN-LAST:event_jExitButtonActionPerformed

    private void jClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jClearButtonActionPerformed
        //Calling the Clear method to set text value of the textfields to null
        Clear();
        
    }//GEN-LAST:event_jClearButtonActionPerformed

    private void jFNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFNameActionPerformed
        
    }//GEN-LAST:event_jFNameActionPerformed

    private void jPatientAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPatientAgeActionPerformed
        
    }//GEN-LAST:event_jPatientAgeActionPerformed

    private void jSNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSNameActionPerformed
        
    }//GEN-LAST:event_jSNameActionPerformed

    private void GenderlistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenderlistActionPerformed
        
    }//GEN-LAST:event_GenderlistActionPerformed

    private void jMenuFileExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuFileExitActionPerformed
        //Closing the Jfram
        System.exit(0);
        
    }//GEN-LAST:event_jMenuFileExitActionPerformed

    private void jMenuEditClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuEditClearActionPerformed
        //Calling the Clear method to set text value of the textfields to null
        Clear();
        
    }//GEN-LAST:event_jMenuEditClearActionPerformed

    private void jMenuHelpAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuHelpAboutActionPerformed
    //Message Dialog for about item in Help menu
    JOptionPane
            .showMessageDialog(frame,
    "Middleware Programming" + "\nRMI Assignment" + "\nSoheil Emadiazar - 21254216" + "\n",
    "About",
    JOptionPane.QUESTION_MESSAGE);    

    }//GEN-LAST:event_jMenuHelpAboutActionPerformed

    private void jMenuEditAoTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuEditAoTONActionPerformed
        //Set JFrame Property to Always Stay on The Top of other windows 
        setAlwaysOnTop(true);
    }//GEN-LAST:event_jMenuEditAoTONActionPerformed

    private void jMenuEditAoTOFFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuEditAoTOFFActionPerformed
        //Set JFrame Property to NOT Always Stay on The Top of other windows 
        setAlwaysOnTop(false); 
    }//GEN-LAST:event_jMenuEditAoTOFFActionPerformed

    private void jMenuFileDoctorsListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuFileDoctorsListActionPerformed
        //Returning the list of Doctors name and Hospital in ResponseBox
        ResponseBox.setText(
                "\nDr.Priscilla Riggs in Croydon Hospital"+
                "\nDr.Dakota Vazquez in Chiltern Hospital"+
                "\nDr.Rogan Schroeder in Herefordshire Hospital"+
                "\nDr.Jemima Dale in Hillingdon Hospital"+
                "\nDr.Elizabeth Freeman in Shropshire Hospital"+
                "\nDr.Alvin Pittman in Luton Hospital"+
                "\nDr.Brenden Vaughn in Sutton Hospital"+
                "\nDr.Wesley Martinez in Reading Hospital"+
                "\nDr.Rhonda Vaughan in Wiltshire Hospital"+
                "\nDr.Zelenia Oneill in Norfolk Hospital"+
                "\nDr.Amela Wolfe in ValeRoyal Hospital"+
                "\nDr.Erasmus Bowman in London Hospital"+
                "\nDr.Illiana Norton in Bristol Hospital");
    }//GEN-LAST:event_jMenuFileDoctorsListActionPerformed
    
    
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {                
                new PatientForm().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList DrList;
    private javax.swing.JComboBox Genderlist;
    private javax.swing.JList HospitalList;
    private javax.swing.JTextArea ResponseBox;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel date_txt;
    private javax.swing.JLabel jAgeError1;
    private javax.swing.JButton jClearButton;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JToggleButton jExitButton;
    private javax.swing.JTextField jFName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuEditAoTOFF;
    private javax.swing.JMenuItem jMenuEditAoTON;
    private javax.swing.JMenuItem jMenuEditClear;
    private javax.swing.JMenuItem jMenuFileDoctorsList;
    private javax.swing.JMenuItem jMenuFileExit;
    private javax.swing.JMenuItem jMenuHelpAbout;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JTextField jPatientAge;
    private javax.swing.JTextField jSName;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JButton jSubmitButton;
    private javax.swing.JLabel time_txt;
    // End of variables declaration//GEN-END:variables

    private LHM LHMAppointment;
    
    public void initWarehouse() {
        //System.setSecurityManager(new RMISecurityManager());
        try {
            String url = "rmi://localhost/LHM-Appointment";
            LHMAppointment = (LHM) Naming.lookup(url);
        } catch (Exception e) {
            System.out.println("Error: Can't connect to LHM-Appointment. " + e);
        }
    }
    
    
    
    private void callWarehouse(Patient c) {
        try {
            Vector recommendations = LHMAppointment.find(c);
            ResponseBox.setText(c + "\n");
            for (int i = 0; i < recommendations.size(); i++) {
                History p = (History) recommendations.get(i);
                String t = p.getDescription() + "\n";
                ResponseBox.append(t);
            }
        } catch (Exception e) {
            ResponseBox.setText("Error: " + e);
        }
    }    
}